model:
  name: image_classifier
  architecture: resnet50
  num_classes: 10

data:
  train_dir: ./data
  test_dir: ./data
  batch_size: 32
  image_size: [32, 32]

training:
  epochs: 30
  learning_rate: .001
  optimizer: adamw
  loss_function: cross_entropy

evaluation:
  metrics: [accuracy, precision, recall]
